version: '3'
services:
  dc3-builder:
    image: gisaia/arlas-datacube-builder:latest
    container_name: dc3-builder
    ports:
      - 8080:5000
    volumes:
      # Input data volume
      - $PWD/tmp/:/app/tmp/
      # Configuration volume
      - $PWD/configs/:/app/configs/
      # Volume to mount for local writing of the datacubes
      - $PWD/output/:/app/output/
    env_file:
      - credentials
